name = "spinogambino-casino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casino.com.es"
HMAC_KEY = "5fa059b5eb834b9002a8653fcdb657c9a98013e3119a922f9855746d29806213"
COOKIE_NAME = "875"
PLAY_PATH = "join-now"
BUTTON_ID = "p3f10e380f4de5cc4daedfcd8f42c6c4b"
GATE_SALT = "42bac88c3ecf07c3"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "zgcy"
CTA_SELECTOR = ".play-button"
